---
title: "Final Project"
author: "Andrew Edelblum, Kivalina Grove, and Ouafaa Hmaddi"
date: "5/20/2019"
output: html_document
---

```{r cleanup, include = FALSE}
library(rio)
library(tidyverse)
library(janitor)
library(colorblindr)
library(stringr)

d <- import("./MasterKickstarter.csv", setclass = "tbl_df") %>% 
  clean_names()

lower48 <- d %>% 
  select(-1:-3) %>% 
  filter(launched_at_y == 13 & 
           country == "USA" & 
           county != "Non-USA" & 
           state != "Non-USA" &
           status != "canceled") %>% 
  mutate(categories = as.factor(categories))

levels(lower48$categories) <- sub("film%20&%20video", "film", levels(lower48$categories))

lower48 <- data.frame(lapply(lower48, function(lower48) {
  if (is.character(lower48)) return(tolower(lower48))
  else return(lower48)
}))

# We looked at inverse of filter to see which cases were in USA == country but were also labeled as county != Non-USA. Those cases were those that were not part of the continental US. We are only looking at Kickstarter campaigns on 2013.

#KH: The piping that you do above is very clear. The use of sub() in conjunction with levels() to essentially rename one of the factor levels in the categories column was helpful to see and is a strategy that I think will definitely be useful to me in the future. 
```

```{r split}
lower48_split <- lower48 %>% 
  split(paste(lower48$state))

#KH: This is a question, really, rather than feedback: I am curious about the possible advantages to using paste() here rather than 
#lower48_split <- split(lower48, lower48$state)
#I imagine there might be advantages, and your line of code is elegant and definitely doing what you want it to do. I just haven't figured out yet what role paste() is playing.

lower48_nest <- lower48 %>%
  group_by(state) %>%
  nest() %>%
  mutate(plot = map2(data, state, ~ggplot(.x, aes(backers_count, log(pledged))) +
                      geom_point(aes(color = categories)) +
                      geom_smooth(se = FALSE) +
                      facet_wrap(~status) +
                      labs(x = "Number of Backers", y = "Amount Pledged ($)", 
                           color = "Categories", 
                           title = "Number of campaign backers and money pledged", 
                           subtitle = glue::glue("Kickstarter data for the state of {.y}")) +
                      scale_color_OkabeIto() +
                      theme_minimal() +
                      theme(plot.title = element_text(face = "bold", hjust = 0.5), 
                      plot.subtitle = element_text(hjust = 0.5),
                      legend.position = "bottom",
                      legend.title = element_text(face = "bold"),
                      axis.title = element_text(face = "bold"))))

#KH: Your nesting by state and your use of map2 to generate a plot for each state exemplify the application of these functions. I see that the y-coordinates represent the logged value of the amount pledged. How might you convey that in the y-axis label?
          
lower48_nest[[3]][4]
```


```{r functionadd}
check_args <- function(data, 
              group_var, 
              sum_var
              ) {
	if(!is.data.frame(data)) {
		stop("Data supplied must be of type data frame.  Data supplied is not a data frame.")
	}
	if(!is.numeric(pull(data, !!enquo(sum_var)))) {
		stop("The variable to summarize must be numeric. The variable supplied is not numeric.")
	}
	if(is.numeric(pull(data, !!enquo(group_var)))) {
		warning("Warning: the grouping variable supplied is numeric, not categorical.")
	}
} 

#KH: I think this function's error messages and warning are nice and clear. I tried the function on a couple of examples below (one that I expected to throw a message, and one for which I didn't expect a message). It worked! It might be helfpul if the function returns something if everything checks out (if arguments are of the expected type). This way the user would get confirmation that the function did something, if that makes sense?

#check_args(lower48, status, goal)
#check_args(lower48, backers_count, goal)

stat_calc <- function(data, 
                      group_var, 
                      outcome_var, 
                      .funs = list(n = ~length(.),
                           n_valid = ~sum(!is.na(.)),
                           n_miss = ~sum(is.na(.)),
                           mean = ~mean(., na.rm = TRUE),
                           sd = ~sd(., na.rm = TRUE),
                           min = ~min(., na.rm = TRUE),
                           max = ~max(., na.rm = TRUE))){
  
  check_args(data, !!enquo(group_var), !!enquo(outcome_var))
  
  data %>%
		group_by(!!enquo(group_var)) %>%
		summarize_at(vars(!!enquo(outcome_var)),
		             .funs)
}

#stat_calc(lower48, status, goal) #KH: Here I was trying out the second function, which worked seamlessly. The use of check_args within stat_calc is effective, and now that I see the way that check_args is deployed within stat_calc, I would take back what I said above about returning something if the arguments check out. In the context of the stat_calc function, of course, the grouped summaries are returned.  
```

